name: Home Still Build

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always


jobs:
  check:
    name: Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt -p hs -p paper -p hs-style --check
      # TODO: Get pdf-mash building too
      - run: cargo clippy --workspace --exclude pdf-mash --all-targets -- -D warnings
      - run: cargo test --workspace --exclude pdf-mash
